// angular-client/src/app/features/debt/communication/communication-dashboard.component.ts
import { Component, inject, signal, computed, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { firstValueFrom } from 'rxjs';
import { ApiService } from '../../../core/services/api.service';
import { ToastService } from '../../../core/services/toast.service';
import { CHANNEL_CONFIG, COMM_STATUS_CONFIG } from '../../../services/debt-config';
import type { CommunicationStats } from '../../../models/debt.models';

type TabMode = 'dashboard' | 'log' | 'scheduled' | 'send';

@Component({
  selector: 'app-communication-dashboard',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './communication-dashboard.component.html',
  styleUrl: './communication-dashboard.component.css'
})
export class CommunicationDashboardComponent implements OnInit {
  private api = inject(ApiService);
  private toast = inject(ToastService);
  private router = inject(Router);

  tab = signal<TabMode>('dashboard');
  stats = signal<CommunicationStats | null>(null);
  statsLoading = signal(false);

  logs = signal<any[]>([]);
  logTotal = signal(0);
  logLoading = signal(false);
  logPage = signal(1);
  logChannel = signal('__all__');
  logStatus = signal('__all__');
  logAccount = signal('');
  logPageSize = 10;

  scheduled = signal<any[]>([]);
  schedTotal = signal(0);
  schedLoading = signal(false);
  schedPage = signal(1);
  schedStatus = signal('__all__');
  processing = signal(false);
  schedPageSize = 10;

  sendChannel = signal('sms');
  sendAccount = signal('');
  sendRecipient = signal('');
  sendSubject = signal('');
  sendMessage = signal('');
  sending = signal(false);
  accountSuggestions = signal<{ accountNo: string; name: string }[]>([]);
  showSuggestions = signal(false);

  logTotalPages = computed(() => Math.ceil(this.logTotal() / this.logPageSize) || 1);
  schedTotalPages = computed(() => Math.ceil(this.schedTotal() / this.schedPageSize) || 1);

  CHANNEL_CONFIG = CHANNEL_CONFIG;
  COMM_STATUS_CONFIG = COMM_STATUS_CONFIG;

  channelEntries = computed(() => {
    const s = this.stats();
    if (!s?.byChannel) return [];
    return Object.entries(s.byChannel).map(([ch, data]) => {
      const cfg = CHANNEL_CONFIG[ch] || CHANNEL_CONFIG['sms'];
      const total = data.sent + data.failed;
      const deliveryRate = total > 0 ? Math.round((data.delivered / total) * 100) : 0;
      return { ch, cfg, data, deliveryRate };
    });
  });

  recipientLabel = computed(() => {
    const ch = this.sendChannel();
    if (ch === 'email') return 'Email Address';
    if (ch === 'letter') return 'Postal Address';
    return 'Mobile Number';
  });

  recipientPlaceholder = computed(() => {
    const ch = this.sendChannel();
    if (ch === 'email') return 'user@example.com';
    if (ch === 'letter') return 'Postal address...';
    return '0821234567';
  });

  ngOnInit(): void {
    this.loadStats();
  }

  setTab(t: TabMode): void {
    this.tab.set(t);
    if (t === 'dashboard') this.loadStats();
    if (t === 'log') this.loadLogs();
    if (t === 'scheduled') this.loadScheduled();
  }

  async loadStats(): Promise<void> {
    this.statsLoading.set(true);
    try {
      const data = await firstValueFrom(this.api.get<CommunicationStats>('/api/communication-stats'));
      this.stats.set(data);
    } catch (err: any) {
      this.toast.error(err?.message || 'Failed to load stats');
    } finally {
      this.statsLoading.set(false);
    }
  }

  async loadLogs(): Promise<void> {
    this.logLoading.set(true);
    try {
      const params: Record<string, string> = {
        limit: String(this.logPageSize),
        offset: String((this.logPage() - 1) * this.logPageSize)
      };
      if (this.logChannel() !== '__all__') params['channel'] = this.logChannel();
      if (this.logStatus() !== '__all__') params['status'] = this.logStatus();
      if (this.logAccount().trim()) params['accountNo'] = this.logAccount().trim();
      const data = await firstValueFrom(this.api.get<any>('/api/communication-log', params));
      this.logs.set(data.logs || []);
      this.logTotal.set(data.total || 0);
    } catch (err: any) {
      this.toast.error(err?.message || 'Failed to load communication log');
    } finally {
      this.logLoading.set(false);
    }
  }

  async loadScheduled(): Promise<void> {
    this.schedLoading.set(true);
    try {
      const params: Record<string, string> = {
        limit: String(this.schedPageSize),
        offset: String((this.schedPage() - 1) * this.schedPageSize)
      };
      if (this.schedStatus() !== '__all__') params['status'] = this.schedStatus();
      const data = await firstValueFrom(this.api.get<any>('/api/scheduled-communications', params));
      this.scheduled.set(data.scheduled || []);
      this.schedTotal.set(data.total || 0);
    } catch (err: any) {
      this.toast.error(err?.message || 'Failed to load scheduled');
    } finally {
      this.schedLoading.set(false);
    }
  }

  async handleProcess(): Promise<void> {
    this.processing.set(true);
    try {
      const result = await firstValueFrom(this.api.post<any>('/api/scheduled-communications/process'));
      this.toast.success(`${result.processed} processed: ${result.succeeded} succeeded, ${result.failed} failed`);
      this.loadScheduled();
      this.loadStats();
    } catch (err: any) {
      this.toast.error(err?.message || 'Processing failed');
    } finally {
      this.processing.set(false);
    }
  }

  async handleAccountSearch(query: string): Promise<void> {
    this.sendAccount.set(query);
    if (query.length >= 3) {
      try {
        const results = await firstValueFrom(this.api.get<any[]>('/api/accounts', { search: query }));
        this.accountSuggestions.set(Array.isArray(results) ? results.slice(0, 8) : []);
        this.showSuggestions.set(true);
      } catch {
        this.accountSuggestions.set([]);
      }
    } else {
      this.accountSuggestions.set([]);
      this.showSuggestions.set(false);
    }
  }

  selectAccount(accountNo: string): void {
    this.sendAccount.set(accountNo);
    this.showSuggestions.set(false);
  }

  hideSuggestions(): void {
    setTimeout(() => this.showSuggestions.set(false), 200);
  }

  async handleSend(): Promise<void> {
    if (!this.sendAccount().trim() || !this.sendRecipient().trim() || !this.sendMessage().trim()) {
      this.toast.error('All fields required');
      return;
    }
    this.sending.set(true);
    try {
      await firstValueFrom(this.api.post<any>('/api/communications/dispatch', {
        accountNo: this.sendAccount().trim(),
        channel: this.sendChannel(),
        recipient: this.sendRecipient().trim(),
        subject: this.sendSubject().trim() || undefined,
        messageBody: this.sendMessage().trim()
      }));
      this.toast.success(`${this.sendChannel().toUpperCase()} dispatched to ${this.sendRecipient()}`);
      this.sendRecipient.set('');
      this.sendSubject.set('');
      this.sendMessage.set('');
    } catch (err: any) {
      this.toast.error(err?.message || 'Send failed');
    } finally {
      this.sending.set(false);
    }
  }

  onLogFilterChange(): void {
    this.logPage.set(1);
    this.loadLogs();
  }

  setLogPage(page: number): void {
    this.logPage.set(page);
    this.loadLogs();
  }

  onSchedFilterChange(): void {
    this.schedPage.set(1);
    this.loadScheduled();
  }

  setSchedPage(page: number): void {
    this.schedPage.set(page);
    this.loadScheduled();
  }

  getChannelLabel(ch: string): string {
    return CHANNEL_CONFIG[ch]?.label || ch;
  }

  getChannelClass(ch: string): string {
    const cfg = CHANNEL_CONFIG[ch] || CHANNEL_CONFIG['sms'];
    return `${cfg.bg} ${cfg.color}`;
  }

  getStatusClass(status: string): string {
    const cfg = COMM_STATUS_CONFIG[status] || COMM_STATUS_CONFIG['PENDING'];
    return `${cfg.bg} ${cfg.color}`;
  }

  formatDate(d: string | null | undefined): string {
    if (!d) return '—';
    try { return new Date(d).toLocaleString(); } catch { return String(d); }
  }

  goHome(): void { this.router.navigate(['/']); }
}

// client/src/pages/debt/communication-dashboard.tsx
import React, { useState, useEffect, useCallback } from 'react';
import { PosLayout } from '@/components/layout/pos-layout';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { HelpTip } from '@/components/ui/help-tip';
import { useToast } from '@/hooks/use-toast';
import { useLocation } from 'wouter';
import {
  Send,
  Loader2,
  Search,
  ChevronLeft,
  ChevronRight,
  ChevronRight as BreadcrumbSep,
  MessageSquare,
  Mail,
  Phone,
  FileText,
  CheckCircle2,
  XCircle,
  Clock,
  BarChart3,
  Play,
  AlertTriangle,
} from 'lucide-react';
import {
  fetchCommunicationLog,
  fetchScheduledCommunications,
  fetchCommunicationStats,
  processScheduledCommunications,
  dispatchCommunication,
  fetchAccounts,
} from '@/lib/external-api';
import { CHANNEL_CONFIG as SHARED_CHANNEL_CONFIG, COMM_STATUS_CONFIG } from '@/services/debt-config';
import type { CommTabMode, CommunicationStats, CommunicationLogEntry } from '@/models/debt.models';

type TabMode = CommTabMode;

const CHANNEL_ICONS: Record<string, any> = {
  sms: Phone,
  email: Mail,
  whatsapp: MessageSquare,
  letter: FileText,
};

const CHANNEL_CONFIG: Record<string, { icon: any; label: string; color: string; bg: string }> = Object.fromEntries(
  Object.entries(SHARED_CHANNEL_CONFIG).map(([key, cfg]) => [
    key,
    { ...cfg, icon: CHANNEL_ICONS[key] || Phone },
  ])
);

const STATUS_CONFIG = COMM_STATUS_CONFIG;

function ChannelBadge({ channel }: { channel: string }) {
  const cfg = CHANNEL_CONFIG[channel] || CHANNEL_CONFIG.sms;
  const Icon = cfg.icon;
  return <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded text-xs font-medium ${cfg.bg} ${cfg.color}`}><Icon className="w-3 h-3" />{cfg.label}</span>;
}

function StatusBadge({ status }: { status: string }) {
  const cfg = STATUS_CONFIG[status] || STATUS_CONFIG.PENDING;
  return <span className={`px-2 py-0.5 rounded text-xs font-semibold ${cfg.bg} ${cfg.color}`}>{status}</span>;
}

export default function CommunicationDashboard() {
  const { toast } = useToast();
  const [, setLocation] = useLocation();
  const [tab, setTab] = useState<TabMode>('dashboard');

  const [stats, setStats] = useState<CommunicationStats | null>(null);
  const [statsLoading, setStatsLoading] = useState(false);

  const [logs, setLogs] = useState<any[]>([]);
  const [logTotal, setLogTotal] = useState(0);
  const [logLoading, setLogLoading] = useState(false);
  const [logPage, setLogPage] = useState(1);
  const [logChannel, setLogChannel] = useState('__all__');
  const [logStatus, setLogStatus] = useState('__all__');
  const [logAccount, setLogAccount] = useState('');
  const logPageSize = 10;

  const [scheduled, setScheduled] = useState<any[]>([]);
  const [schedTotal, setSchedTotal] = useState(0);
  const [schedLoading, setSchedLoading] = useState(false);
  const [schedPage, setSchedPage] = useState(1);
  const [schedStatus, setSchedStatus] = useState('__all__');
  const [processing, setProcessing] = useState(false);
  const schedPageSize = 10;

  const [sendChannel, setSendChannel] = useState('sms');
  const [sendAccount, setSendAccount] = useState('');
  const [sendRecipient, setSendRecipient] = useState('');
  const [sendSubject, setSendSubject] = useState('');
  const [sendMessage, setSendMessage] = useState('');
  const [sending, setSending] = useState(false);
  const [accountSuggestions, setAccountSuggestions] = useState<{ accountNo: string; name: string }[]>([]);
  const [showSuggestions, setShowSuggestions] = useState(false);

  const loadStats = useCallback(async () => {
    setStatsLoading(true);
    try {
      const data = await fetchCommunicationStats();
      setStats(data);
    } catch (err: any) {
      toast({ title: 'Failed to load stats', description: err.message, variant: 'destructive' });
    } finally { setStatsLoading(false); }
  }, []);

  const loadLogs = useCallback(async () => {
    setLogLoading(true);
    try {
      const params: Record<string, string> = { limit: String(logPageSize), offset: String((logPage - 1) * logPageSize) };
      if (logChannel !== '__all__') params.channel = logChannel;
      if (logStatus !== '__all__') params.status = logStatus;
      if (logAccount.trim()) params.accountNo = logAccount.trim();
      const data = await fetchCommunicationLog(params);
      setLogs(data.logs || []);
      setLogTotal(data.total || 0);
    } catch (err: any) {
      toast({ title: 'Failed to load communication log', description: err.message, variant: 'destructive' });
    } finally { setLogLoading(false); }
  }, [logPage, logChannel, logStatus, logAccount]);

  const loadScheduled = useCallback(async () => {
    setSchedLoading(true);
    try {
      const params: Record<string, string> = { limit: String(schedPageSize), offset: String((schedPage - 1) * schedPageSize) };
      if (schedStatus !== '__all__') params.status = schedStatus;
      const data = await fetchScheduledCommunications(params);
      setScheduled(data.scheduled || []);
      setSchedTotal(data.total || 0);
    } catch (err: any) {
      toast({ title: 'Failed to load scheduled', description: err.message, variant: 'destructive' });
    } finally { setSchedLoading(false); }
  }, [schedPage, schedStatus]);

  const handleProcess = async () => {
    setProcessing(true);
    try {
      const result = await processScheduledCommunications();
      toast({ title: 'Processing Complete', description: `${result.processed} processed: ${result.succeeded} succeeded, ${result.failed} failed` });
      loadScheduled();
      loadStats();
    } catch (err: any) {
      toast({ title: 'Processing Failed', description: err.message, variant: 'destructive' });
    } finally { setProcessing(false); }
  };

  const handleAccountSearch = useCallback(async (query: string) => {
    setSendAccount(query);
    if (query.length >= 3) {
      try {
        const results = await fetchAccounts(query);
        setAccountSuggestions(Array.isArray(results) ? results.slice(0, 8) : []);
        setShowSuggestions(true);
      } catch { setAccountSuggestions([]); }
    } else { setAccountSuggestions([]); setShowSuggestions(false); }
  }, []);

  const handleSend = async () => {
    if (!sendAccount.trim() || !sendRecipient.trim() || !sendMessage.trim()) {
      toast({ title: 'All fields required', variant: 'destructive' }); return;
    }
    setSending(true);
    try {
      await dispatchCommunication({ accountNo: sendAccount.trim(), channel: sendChannel, recipient: sendRecipient.trim(), subject: sendSubject.trim() || undefined, messageBody: sendMessage.trim() });
      toast({ title: 'Communication Sent', description: `${sendChannel.toUpperCase()} dispatched to ${sendRecipient}` });
      setSendRecipient('');
      setSendSubject('');
      setSendMessage('');
    } catch (err: any) {
      toast({ title: 'Send Failed', description: err.message, variant: 'destructive' });
    } finally { setSending(false); }
  };

  useEffect(() => { if (tab === 'dashboard') loadStats(); }, [tab, loadStats]);
  useEffect(() => { if (tab === 'log') loadLogs(); }, [tab, loadLogs]);
  useEffect(() => { if (tab === 'scheduled') loadScheduled(); }, [tab, loadScheduled]);

  const logTotalPages = Math.ceil(logTotal / logPageSize);
  const schedTotalPages = Math.ceil(schedTotal / schedPageSize);

  return (
    <PosLayout>
      <div className="flex flex-col h-full overflow-hidden">
        <div className="shrink-0 px-4 pt-3 pb-2 border-b border-[#D6D6D6] bg-white">
          <div className="flex items-center gap-2 text-sm text-muted-foreground mb-2">
            <button onClick={() => setLocation('/')} className="hover:text-foreground transition-colors" data-testid="link-home">Home</button>
            <BreadcrumbSep className="w-3 h-3" />
            <span className="text-foreground font-medium">Communication Dashboard</span>
          </div>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-[var(--pos-accent)] to-[var(--pos-accent-dark)] shadow-[0_1px_3px_rgba(0,0,0,0.15)] flex items-center justify-center">
                <Send className="w-4 h-4 text-white" />
              </div>
              <h1 className="text-lg font-semibold text-foreground">Omni-Channel Communication Dashboard</h1>
              <HelpTip text="Monitor delivery status across all communication channels — SMS, Email, WhatsApp, and printed letters. Track scheduled communications and dispatch ad-hoc messages." />
            </div>
            <div className="flex gap-1">
              {(['dashboard', 'log', 'scheduled', 'send'] as TabMode[]).map(t => (
                <Button key={t} size="sm" variant={tab === t ? 'default' : 'ghost'} onClick={() => setTab(t)} className={tab === t ? 'bg-[var(--pos-accent)] hover:bg-[var(--pos-accent-dark)] text-white font-semibold rounded-lg shadow-sm' : 'text-muted-foreground hover:text-foreground'} data-testid={`tab-${t}`}>
                  {t === 'dashboard' && <><BarChart3 className="w-3.5 h-3.5 mr-1" />Overview</>}
                  {t === 'log' && <><FileText className="w-3.5 h-3.5 mr-1" />Log</>}
                  {t === 'scheduled' && <><Clock className="w-3.5 h-3.5 mr-1" />Scheduled</>}
                  {t === 'send' && <><Send className="w-3.5 h-3.5 mr-1" />Send</>}
                </Button>
              ))}
            </div>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto bg-[#F2F4F7] min-h-0">
          <div className="max-w-7xl mx-auto p-3 sm:p-4 lg:p-6 space-y-4">
          {tab === 'dashboard' && (
            <>
              {statsLoading ? (
                <div className="flex items-center justify-center py-12"><Loader2 className="w-8 h-8 animate-spin text-muted-foreground" /></div>
              ) : !stats ? (
                <div className="text-center py-12 text-muted-foreground">No communication data yet.</div>
              ) : (
                <>
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                    <Card className="bg-white border-[#D6D6D6] shadow-sm rounded-xl"><CardContent className="p-3 flex items-center gap-3"><div className="w-8 h-8 rounded-lg bg-gradient-to-br from-[var(--pos-accent)] to-[var(--pos-accent-dark)] flex items-center justify-center"><Send className="w-4 h-4 text-white" /></div><div><div className="text-xl font-bold text-foreground" data-testid="text-total-sent">{stats.totalSent}</div><div className="text-xs text-muted-foreground">Total Sent</div></div></CardContent></Card>
                    <Card className="bg-emerald-50 border-emerald-200 rounded-xl"><CardContent className="p-3 flex items-center gap-3"><CheckCircle2 className="w-8 h-8 text-emerald-700" /><div><div className="text-xl font-bold text-emerald-700" data-testid="text-total-delivered">{stats.totalDelivered}</div><div className="text-xs text-emerald-600">Delivered</div></div></CardContent></Card>
                    <Card className="bg-red-50 border-red-200 rounded-xl"><CardContent className="p-3 flex items-center gap-3"><XCircle className="w-8 h-8 text-red-700" /><div><div className="text-xl font-bold text-red-700" data-testid="text-total-failed">{stats.totalFailed}</div><div className="text-xs text-red-600">Failed</div></div></CardContent></Card>
                    <Card className="bg-amber-50 border-amber-200 rounded-xl"><CardContent className="p-3 flex items-center gap-3"><Clock className="w-8 h-8 text-amber-700" /><div><div className="text-xl font-bold text-amber-700" data-testid="text-total-pending">{stats.totalPending}</div><div className="text-xs text-amber-600">Pending</div></div></CardContent></Card>
                  </div>

                  <Card className="bg-white border-[#D6D6D6] shadow-sm rounded-xl">
                    <CardContent className="p-4">
                      <h3 className="text-sm font-semibold text-foreground mb-3">Delivery by Channel</h3>
                      {Object.keys(stats.byChannel || {}).length === 0 ? (
                        <div className="text-center py-6 text-muted-foreground text-sm">No channel data yet. Send communications to see delivery stats.</div>
                      ) : (
                        <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                          {Object.entries(stats.byChannel as Record<string, { sent: number; delivered: number; failed: number }>).map(([ch, data]) => {
                            const cfg = CHANNEL_CONFIG[ch] || CHANNEL_CONFIG.sms;
                            const Icon = cfg.icon;
                            const total = data.sent + data.failed;
                            const deliveryRate = total > 0 ? Math.round((data.delivered / total) * 100) : 0;
                            return (
                              <Card key={ch} className="bg-[#F7F7F7] border-[#D6D6D6] rounded-xl">
                                <CardContent className="p-3 space-y-2">
                                  <div className="flex items-center gap-2">
                                    <Icon className={`w-5 h-5 ${cfg.color}`} />
                                    <span className="text-sm font-medium text-foreground">{cfg.label}</span>
                                  </div>
                                  <div className="grid grid-cols-3 gap-1 text-center">
                                    <div><div className="text-lg font-bold text-foreground">{data.sent}</div><div className="text-[10px] text-muted-foreground">Sent</div></div>
                                    <div><div className="text-lg font-bold text-emerald-700">{data.delivered}</div><div className="text-[10px] text-muted-foreground">Delivered</div></div>
                                    <div><div className="text-lg font-bold text-red-700">{data.failed}</div><div className="text-[10px] text-muted-foreground">Failed</div></div>
                                  </div>
                                  <div className="h-1.5 bg-[#E5E5E5] rounded-full overflow-hidden">
                                    <div className="h-full bg-emerald-500 rounded-full" style={{ width: `${deliveryRate}%` }} />
                                  </div>
                                  <div className="text-[10px] text-muted-foreground text-center">{deliveryRate}% delivery rate</div>
                                </CardContent>
                              </Card>
                            );
                          })}
                        </div>
                      )}
                    </CardContent>
                  </Card>
                </>
              )}
            </>
          )}

          {tab === 'log' && (
            <Card className="bg-white border-[#D6D6D6] shadow-sm rounded-xl">
              <CardContent className="p-4">
                <div className="flex items-center justify-between mb-3">
                  <h3 className="text-sm font-semibold text-foreground">Communication Log</h3>
                  <div className="flex gap-2">
                    <Input value={logAccount} onChange={e => { setLogAccount(e.target.value); setLogPage(1); }} placeholder="Account..." className="w-32 bg-[#F7F7F7] border-[#D6D6D6] h-8 text-xs" data-testid="input-log-account" />
                    <Select value={logChannel} onValueChange={v => { setLogChannel(v); setLogPage(1); }}>
                      <SelectTrigger className="w-28 bg-[#F7F7F7] border-[#D6D6D6] h-8 text-xs"><SelectValue /></SelectTrigger>
                      <SelectContent>
                        <SelectItem value="__all__">All Channels</SelectItem>
                        <SelectItem value="sms">SMS</SelectItem>
                        <SelectItem value="email">Email</SelectItem>
                        <SelectItem value="whatsapp">WhatsApp</SelectItem>
                        <SelectItem value="letter">Letter</SelectItem>
                      </SelectContent>
                    </Select>
                    <Select value={logStatus} onValueChange={v => { setLogStatus(v); setLogPage(1); }}>
                      <SelectTrigger className="w-24 bg-[#F7F7F7] border-[#D6D6D6] h-8 text-xs"><SelectValue /></SelectTrigger>
                      <SelectContent>
                        <SelectItem value="__all__">All Status</SelectItem>
                        <SelectItem value="SENT">Sent</SelectItem>
                        <SelectItem value="FAILED">Failed</SelectItem>
                        <SelectItem value="PENDING">Pending</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>
                {logLoading ? (
                  <div className="flex items-center justify-center py-8"><Loader2 className="w-6 h-6 animate-spin text-muted-foreground" /></div>
                ) : logs.length === 0 ? (
                  <div className="text-center py-8 text-muted-foreground text-sm">No communication records found.</div>
                ) : (
                  <>
                    <div className="overflow-x-auto">
                      <Table>
                        <TableHeader>
                          <TableRow className="border-[#E5E5E5] hover:bg-transparent bg-[#F7F7F7]">
                            <TableHead className="text-[11px] font-medium text-muted-foreground uppercase tracking-wider">Account</TableHead>
                            <TableHead className="text-[11px] font-medium text-muted-foreground uppercase tracking-wider">Channel</TableHead>
                            <TableHead className="text-[11px] font-medium text-muted-foreground uppercase tracking-wider">Recipient</TableHead>
                            <TableHead className="text-[11px] font-medium text-muted-foreground uppercase tracking-wider">Status</TableHead>
                            <TableHead className="text-[11px] font-medium text-muted-foreground uppercase tracking-wider">Delivery</TableHead>
                            <TableHead className="text-[11px] font-medium text-muted-foreground uppercase tracking-wider">Sent By</TableHead>
                            <TableHead className="text-[11px] font-medium text-muted-foreground uppercase tracking-wider">Date</TableHead>
                          </TableRow>
                        </TableHeader>
                        <TableBody className="divide-y divide-[#E5E5E5]">
                          {logs.map((log: any, i: number) => (
                            <TableRow key={i} className="hover:bg-[var(--pos-accent-hover-row)]" data-testid={`row-log-${i}`}>
                              <TableCell className="text-foreground text-sm font-mono">{log.accountNo || log.account_no}</TableCell>
                              <TableCell><ChannelBadge channel={log.channel} /></TableCell>
                              <TableCell className="text-foreground text-sm">{log.recipient || '-'}</TableCell>
                              <TableCell><StatusBadge status={log.status} /></TableCell>
                              <TableCell><StatusBadge status={log.deliveryStatus || log.delivery_status || 'PENDING'} /></TableCell>
                              <TableCell className="text-muted-foreground text-sm">{log.sentBy || log.sent_by || '-'}</TableCell>
                              <TableCell className="text-muted-foreground text-sm">{log.sentAt || log.sent_at ? new Date(log.sentAt || log.sent_at).toLocaleString() : '-'}</TableCell>
                            </TableRow>
                          ))}
                        </TableBody>
                      </Table>
                    </div>
                    <div className="flex items-center justify-between mt-3 text-xs text-muted-foreground">
                      <span>{logTotal} total records</span>
                      <div className="flex items-center gap-2">
                        <Button size="sm" variant="ghost" onClick={() => setLogPage(p => Math.max(1, p - 1))} disabled={logPage <= 1} className="text-muted-foreground h-7"><ChevronLeft className="w-3.5 h-3.5" /></Button>
                        <span>Page {logPage} of {logTotalPages || 1}</span>
                        <Button size="sm" variant="ghost" onClick={() => setLogPage(p => Math.min(logTotalPages, p + 1))} disabled={logPage >= logTotalPages} className="text-muted-foreground h-7"><ChevronRight className="w-3.5 h-3.5" /></Button>
                      </div>
                    </div>
                  </>
                )}
              </CardContent>
            </Card>
          )}

          {tab === 'scheduled' && (
            <>
              <div className="flex items-center justify-between">
                <div className="flex gap-2">
                  <Select value={schedStatus} onValueChange={v => { setSchedStatus(v); setSchedPage(1); }}>
                    <SelectTrigger className="w-32 bg-[#F7F7F7] border-[#D6D6D6] h-9" data-testid="select-sched-status"><SelectValue /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="__all__">All Status</SelectItem>
                      <SelectItem value="PENDING">Pending</SelectItem>
                      <SelectItem value="COMPLETED">Completed</SelectItem>
                      <SelectItem value="FAILED">Failed</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <Button onClick={handleProcess} disabled={processing} className="bg-[var(--pos-accent)] hover:bg-[var(--pos-accent-dark)] text-white font-semibold rounded-lg shadow-sm" data-testid="button-process">
                  {processing ? <Loader2 className="w-4 h-4 mr-1 animate-spin" /> : <Play className="w-4 h-4 mr-1" />}Process Due Communications
                </Button>
              </div>
              <Card className="bg-white border-[#D6D6D6] shadow-sm rounded-xl">
                <CardContent className="p-4">
                  {schedLoading ? (
                    <div className="flex items-center justify-center py-8"><Loader2 className="w-6 h-6 animate-spin text-muted-foreground" /></div>
                  ) : scheduled.length === 0 ? (
                    <div className="text-center py-8 text-muted-foreground text-sm">No scheduled communications found. Enroll accounts in a timeline to schedule automated messages.</div>
                  ) : (
                    <>
                      <div className="overflow-x-auto">
                        <Table>
                          <TableHeader>
                            <TableRow className="border-[#E5E5E5] hover:bg-transparent bg-[#F7F7F7]">
                              <TableHead className="text-[11px] font-medium text-muted-foreground uppercase tracking-wider">Account</TableHead>
                              <TableHead className="text-[11px] font-medium text-muted-foreground uppercase tracking-wider">Scheduled Date</TableHead>
                              <TableHead className="text-[11px] font-medium text-muted-foreground uppercase tracking-wider">Status</TableHead>
                              <TableHead className="text-[11px] font-medium text-muted-foreground uppercase tracking-wider">Processed</TableHead>
                            </TableRow>
                          </TableHeader>
                          <TableBody className="divide-y divide-[#E5E5E5]">
                            {scheduled.map((s: any, i: number) => (
                              <TableRow key={i} className="hover:bg-[var(--pos-accent-hover-row)]" data-testid={`row-sched-${i}`}>
                                <TableCell className="text-foreground text-sm font-mono">{s.accountNo || s.account_no}</TableCell>
                                <TableCell className="text-foreground text-sm">{s.scheduledDate || s.scheduled_date ? new Date(s.scheduledDate || s.scheduled_date).toLocaleString() : '-'}</TableCell>
                                <TableCell><StatusBadge status={s.status} /></TableCell>
                                <TableCell className="text-muted-foreground text-sm">{s.processedAt || s.processed_at ? new Date(s.processedAt || s.processed_at).toLocaleString() : '-'}</TableCell>
                              </TableRow>
                            ))}
                          </TableBody>
                        </Table>
                      </div>
                      <div className="flex items-center justify-between mt-3 text-xs text-muted-foreground">
                        <span>{schedTotal} total</span>
                        <div className="flex items-center gap-2">
                          <Button size="sm" variant="ghost" onClick={() => setSchedPage(p => Math.max(1, p - 1))} disabled={schedPage <= 1} className="text-muted-foreground h-7"><ChevronLeft className="w-3.5 h-3.5" /></Button>
                          <span>Page {schedPage} of {schedTotalPages || 1}</span>
                          <Button size="sm" variant="ghost" onClick={() => setSchedPage(p => Math.min(schedTotalPages, p + 1))} disabled={schedPage >= schedTotalPages} className="text-muted-foreground h-7"><ChevronRight className="w-3.5 h-3.5" /></Button>
                        </div>
                      </div>
                    </>
                  )}
                </CardContent>
              </Card>
            </>
          )}

          {tab === 'send' && (
            <Card className="bg-white border-[#D6D6D6] shadow-sm rounded-xl">
              <CardContent className="p-4 space-y-3">
                <h3 className="text-sm font-semibold text-foreground flex items-center gap-2"><Send className="w-4 h-4" />Send Ad-Hoc Communication</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  <div className="relative">
                    <Label className="text-xs text-muted-foreground">Account Number</Label>
                    <Input data-testid="input-send-account" value={sendAccount} onChange={e => handleAccountSearch(e.target.value)} onBlur={() => setTimeout(() => setShowSuggestions(false), 200)} placeholder="Search account..." className="bg-[#F7F7F7] border-[#D6D6D6] h-9" />
                    {showSuggestions && accountSuggestions.length > 0 && (
                      <div className="absolute z-50 w-full mt-1 bg-white border border-[#D6D6D6] rounded-md shadow-lg max-h-32 overflow-y-auto">
                        {accountSuggestions.map((s, i) => (
                          <button key={i} className="w-full text-left px-3 py-1.5 text-sm text-foreground hover:bg-[var(--pos-accent-hover-row)]" onClick={() => { setSendAccount(s.accountNo); setShowSuggestions(false); }}>{s.accountNo} — {s.name}</button>
                        ))}
                      </div>
                    )}
                  </div>
                  <div>
                    <Label className="text-xs text-muted-foreground">Channel</Label>
                    <Select value={sendChannel} onValueChange={setSendChannel}>
                      <SelectTrigger className="bg-[#F7F7F7] border-[#D6D6D6] h-9" data-testid="select-send-channel"><SelectValue /></SelectTrigger>
                      <SelectContent>
                        <SelectItem value="sms">SMS</SelectItem>
                        <SelectItem value="email">Email</SelectItem>
                        <SelectItem value="whatsapp">WhatsApp</SelectItem>
                        <SelectItem value="letter">Printed Letter</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  <div>
                    <Label className="text-xs text-muted-foreground">Recipient ({sendChannel === 'email' ? 'Email Address' : sendChannel === 'letter' ? 'Postal Address' : 'Mobile Number'})</Label>
                    <Input data-testid="input-send-recipient" value={sendRecipient} onChange={e => setSendRecipient(e.target.value)} placeholder={sendChannel === 'email' ? 'user@example.com' : sendChannel === 'letter' ? 'Postal address...' : '0821234567'} className="bg-[#F7F7F7] border-[#D6D6D6] h-9" />
                  </div>
                  {(sendChannel === 'email' || sendChannel === 'letter') && (
                    <div>
                      <Label className="text-xs text-muted-foreground">Subject</Label>
                      <Input data-testid="input-send-subject" value={sendSubject} onChange={e => setSendSubject(e.target.value)} placeholder="Subject line..." className="bg-[#F7F7F7] border-[#D6D6D6] h-9" />
                    </div>
                  )}
                </div>
                <div>
                  <Label className="text-xs text-muted-foreground">Message</Label>
                  <textarea data-testid="textarea-send-message" value={sendMessage} onChange={e => setSendMessage(e.target.value)} className="w-full h-28 bg-[#F7F7F7] border border-[#D6D6D6] text-foreground text-sm rounded-md p-2 resize-none focus:ring-2 focus:ring-[var(--pos-accent)] focus:border-transparent" placeholder="Enter your message..." />
                </div>
                <Button onClick={handleSend} disabled={sending} className="bg-[var(--pos-accent)] hover:bg-[var(--pos-accent-dark)] text-white font-semibold rounded-lg shadow-sm" data-testid="button-send">
                  {sending ? <Loader2 className="w-4 h-4 mr-1 animate-spin" /> : <Send className="w-4 h-4 mr-1" />}
                  Send {CHANNEL_CONFIG[sendChannel]?.label || 'Message'}
                </Button>
              </CardContent>
            </Card>
          )}
          </div>
        </div>
      </div>
    </PosLayout>
  );
}
