// angular-client/src/app/features/debt/section129/section129-trial-review.component.ts
import { Component, signal, computed, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, ActivatedRoute } from '@angular/router';
import { firstValueFrom } from 'rxjs';
import { ApiService } from '../../../core/services/api.service';
import { ToastService } from '../../../core/services/toast.service';
import { getStatusColor } from '../../../services/validation.service';
import { PAGE_SIZE } from '../../../services/debt-config';
import type { Section129Run, Section129RunAccount } from '../../../models/debt.models';

@Component({
  selector: 'app-section129-trial-review',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './section129-trial-review.component.html',
  styleUrl: './section129-trial-review.component.css'
})
export class Section129TrialReviewComponent implements OnInit {
  runId = 0;
  accounts = signal<Section129RunAccount[]>([]);
  runInfo = signal<Section129Run | null>(null);
  loading = signal(true);
  submitting = signal(false);
  selectedIds = new Set<number>();
  finalReviewComplete = false;
  currentPage = 1;
  pageSize = PAGE_SIZE;

  constructor(
    private api: ApiService,
    private toast: ToastService,
    private router: Router,
    private route: ActivatedRoute
  ) {}

  ngOnInit(): void {
    this.runId = parseInt(this.route.snapshot.paramMap.get('runId') || '0', 10);
    if (this.runId) this.loadData();
  }

  async loadData(): Promise<void> {
    this.loading.set(true);
    try {
      const [accountsData, runsData] = await Promise.all([
        firstValueFrom(this.api.get(`/api/section129/runs/${this.runId}/accounts`)),
        firstValueFrom(this.api.get('/api/section129/runs')),
      ]);
      this.accounts.set(accountsData || []);
      const run = (runsData || []).find((r: Section129Run) => r.runId === this.runId) || null;
      this.runInfo.set(run);
      const preSelected = new Set<number>(
        (accountsData || []).filter((a: Section129RunAccount) => a.selected).map((a: Section129RunAccount) => a.accountId)
      );
      this.selectedIds = preSelected.size > 0 ? preSelected : new Set<number>((accountsData || []).map((a: Section129RunAccount) => a.accountId));
    } catch (err: any) {
      this.toast.show(err?.error?.message || err?.message || 'Could not load trial run accounts.', 'error');
    } finally {
      this.loading.set(false);
    }
  }

  get totalPages(): number {
    return Math.ceil(this.accounts().length / this.pageSize);
  }

  get paginatedAccounts(): Section129RunAccount[] {
    const start = (this.currentPage - 1) * this.pageSize;
    return this.accounts().slice(start, start + this.pageSize);
  }

  get allOnPageSelected(): boolean {
    const page = this.paginatedAccounts;
    if (page.length === 0) return false;
    return page.every(a => this.selectedIds.has(a.accountId));
  }

  get totalQualifyingAmount(): number {
    return this.accounts()
      .filter(a => this.selectedIds.has(a.accountId))
      .reduce((sum, a) => sum + (a.qualifyingAmount || 0), 0);
  }

  get totalNoticeFees(): number {
    return this.accounts()
      .filter(a => this.selectedIds.has(a.accountId))
      .reduce((sum, a) => sum + (a.noticeFees || 0), 0);
  }

  isSelected(accountId: number): boolean {
    return this.selectedIds.has(accountId);
  }

  toggleAccount(accountId: number): void {
    if (this.selectedIds.has(accountId)) {
      this.selectedIds.delete(accountId);
    } else {
      this.selectedIds.add(accountId);
    }
    this.selectedIds = new Set(this.selectedIds);
  }

  toggleSelectAll(): void {
    const page = this.paginatedAccounts;
    if (this.allOnPageSelected) {
      page.forEach(a => this.selectedIds.delete(a.accountId));
    } else {
      page.forEach(a => this.selectedIds.add(a.accountId));
    }
    this.selectedIds = new Set(this.selectedIds);
  }

  getStatusColor(status: string): string {
    return getStatusColor(status);
  }

  formatCurrency(value: number): string {
    return `R ${(value || 0).toLocaleString('en-ZA', { minimumFractionDigits: 2 })}`;
  }

  getDaysClass(days: number): string {
    if (days > 90) return 'text-danger';
    if (days > 60) return 'text-warning';
    return '';
  }

  async handleSubmit(): Promise<void> {
    if (this.selectedIds.size === 0) {
      this.toast.show('Please select at least one account before submitting.', 'error');
      return;
    }
    this.submitting.set(true);
    try {
      const result: any = await firstValueFrom(this.api.post('/api/section129/trial-review', {
        runId: this.runId,
        selectedAccountIds: Array.from(this.selectedIds),
        finalReviewComplete: this.finalReviewComplete,
      }));
      this.toast.show(result?.message || `Successfully submitted review for ${this.selectedIds.size} account(s).`, 'success');
      this.router.navigate(['/debt/section129']);
    } catch (err: any) {
      this.toast.show(err?.error?.message || err?.message || 'Failed to submit trial review.', 'error');
    } finally {
      this.submitting.set(false);
    }
  }

  goBack(): void {
    this.router.navigate(['/debt/section129']);
  }

  prevPage(): void {
    if (this.currentPage > 1) this.currentPage--;
  }

  nextPage(): void {
    if (this.currentPage < this.totalPages) this.currentPage++;
  }
}

<div class="page-container">
  <div class="page-header">
    <button class="btn btn-ghost" (click)="goBack()" data-testid="button-back">← Back to Notices</button>
    <div>
      <h1 class="page-title" data-testid="text-page-title">Trial Run Review</h1>
      <p class="page-subtitle">Review and select accounts for Section 129 notice processing</p>
    </div>
  </div>

  <div class="card run-info-card">
    <div class="card-body run-info">
      <div class="info-item">
        <span class="info-label">Run ID</span>
        <span class="info-value" data-testid="text-run-id">{{ runId || '—' }}</span>
      </div>
      <div class="info-item">
        <span class="info-label">Status</span>
        <span class="badge" [class]="getStatusColor(runInfo()?.status || '')" data-testid="badge-run-status">{{ runInfo()?.status || 'Loading...' }}</span>
      </div>
      <div class="info-item">
        <span class="info-label">Handover Option</span>
        <span class="info-value" data-testid="text-handover-option">{{ runInfo()?.handoverOption || '—' }}</span>
      </div>
      <div class="info-item">
        <span class="info-label">Created</span>
        <span class="info-value" data-testid="text-date-created">{{ runInfo()?.dateCreated || '—' }}</span>
      </div>
    </div>
  </div>

  <div class="stats-grid">
    <div class="stat-card">
      <div class="stat-label">Total Accounts</div>
      <div class="stat-value" data-testid="text-total-accounts">{{ accounts().length }}</div>
    </div>
    <div class="stat-card">
      <div class="stat-label">Selected</div>
      <div class="stat-value stat-blue" data-testid="text-selected-count">{{ selectedIds.size }}</div>
    </div>
    <div class="stat-card">
      <div class="stat-label">Qualifying Amount</div>
      <div class="stat-value stat-green" data-testid="text-qualifying-total">{{ formatCurrency(totalQualifyingAmount) }}</div>
    </div>
    <div class="stat-card">
      <div class="stat-label">Notice Fees</div>
      <div class="stat-value stat-amber" data-testid="text-fees-total">{{ formatCurrency(totalNoticeFees) }}</div>
    </div>
  </div>

  <div class="card">
    @if (loading()) {
      <div class="loading-center">
        <span class="spinner spinner-lg"></span>
        <p>Loading trial run accounts...</p>
      </div>
    } @else if (accounts().length === 0) {
      <div class="loading-center">
        <p class="text-muted">No accounts found for this trial run.</p>
        <button class="btn btn-outline" (click)="goBack()" data-testid="button-back-empty">Back to Notices</button>
      </div>
    } @else {
      <div class="table-container">
        <table>
          <thead>
            <tr>
              <th style="width:2.5rem">
                <input type="checkbox" [checked]="allOnPageSelected" (change)="toggleSelectAll()" data-testid="checkbox-select-all" />
              </th>
              <th>Account No</th>
              <th>Address</th>
              <th>Indigent</th>
              <th>Rebate</th>
              <th>SG Number</th>
              <th class="text-right">Days O/S</th>
              <th class="text-right">Qualifying Amt</th>
              <th class="text-right">Notice Fees</th>
            </tr>
          </thead>
          <tbody>
            @for (account of paginatedAccounts; track account.accountId) {
              <tr [class.selected-row]="isSelected(account.accountId)" class="clickable" (click)="toggleAccount(account.accountId)" [attr.data-testid]="'row-account-' + account.accountId">
                <td (click)="$event.stopPropagation()">
                  <input type="checkbox" [checked]="isSelected(account.accountId)" (change)="toggleAccount(account.accountId)" [attr.data-testid]="'checkbox-account-' + account.accountId" />
                </td>
                <td class="font-medium" [attr.data-testid]="'text-account-no-' + account.accountId">{{ account.accountNo }}</td>
                <td class="text-muted truncate-cell" [title]="account.address">{{ account.address || '—' }}</td>
                <td>
                  <span class="badge" [class]="account.indigentStatus?.toLowerCase() === 'yes' ? 'badge-orange' : 'badge-slate'" [attr.data-testid]="'badge-indigent-' + account.accountId">{{ account.indigentStatus || 'No' }}</span>
                </td>
                <td>
                  <span class="badge" [class]="account.rebateStatus?.toLowerCase() === 'yes' ? 'badge-purple' : 'badge-slate'" [attr.data-testid]="'badge-rebate-' + account.accountId">{{ account.rebateStatus || 'No' }}</span>
                </td>
                <td class="font-mono text-muted">{{ account.sgNumber || '—' }}</td>
                <td class="text-right font-medium" [class]="getDaysClass(account.outstandingDays)" [attr.data-testid]="'text-days-' + account.accountId">{{ account.outstandingDays }}</td>
                <td class="text-right font-medium" [attr.data-testid]="'text-amount-' + account.accountId">{{ formatCurrency(account.qualifyingAmount) }}</td>
                <td class="text-right text-muted">{{ formatCurrency(account.noticeFees) }}</td>
              </tr>
            }
          </tbody>
        </table>
      </div>

      @if (totalPages > 1) {
        <div class="pagination">
          <span class="pagination-info" data-testid="text-pagination-info">Page {{ currentPage }} of {{ totalPages }} ({{ accounts().length }} accounts)</span>
          <div class="pagination-buttons">
            <button class="btn btn-outline btn-sm" (click)="prevPage()" [disabled]="currentPage <= 1" data-testid="button-prev-page">‹</button>
            <button class="btn btn-outline btn-sm" (click)="nextPage()" [disabled]="currentPage >= totalPages" data-testid="button-next-page">›</button>
          </div>
        </div>
      }
    }
  </div>

  @if (!loading() && accounts().length > 0) {
    <div class="card">
      <div class="card-body review-footer">
        <div class="toggle-item">
          <input type="checkbox" id="final-review" [(ngModel)]="finalReviewComplete" data-testid="switch-final-review" />
          <label for="final-review" class="font-medium">Final Review Complete</label>
          @if (finalReviewComplete) {
            <span class="check-icon">✓</span>
          }
        </div>
        <div class="footer-buttons">
          <button class="btn btn-outline" (click)="goBack()" data-testid="button-cancel">Cancel</button>
          <button class="btn btn-primary" (click)="handleSubmit()" [disabled]="submitting() || selectedIds.size === 0" data-testid="button-submit">
            @if (submitting()) { <span class="spinner"></span> }
            Submit Review ({{ selectedIds.size }})
          </button>
        </div>
      </div>
    </div>
  }
</div>

// client/src/pages/debt/section129-trial-review.tsx
import React, { useState, useEffect, useMemo, useCallback } from 'react';
import { PosLayout } from '@/components/layout/pos-layout';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Checkbox } from '@/components/ui/checkbox';
import { Switch } from '@/components/ui/switch';
import { Label } from '@/components/ui/label';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { HelpTip } from '@/components/ui/help-tip';
import { useToast } from '@/hooks/use-toast';
import { useLocation, useParams } from 'wouter';
import {
  fetchSection129RunAccounts,
  fetchSection129Runs,
  submitSection129TrialReview,
  type Section129RunAccount,
  type Section129Run,
} from '@/lib/external-api';
import {
  Loader2,
  ChevronLeft,
  ChevronRight,
  FileCheck,
  AlertTriangle,
  CheckCircle2,
  XCircle,
  Send,
  ArrowLeft,
  Users,
  Hash,
  MapPin,
  Shield,
  Tag,
  Clock,
  DollarSign,
  Receipt,
} from 'lucide-react';
import { PAGE_SIZE } from '@/services/debt-config';
import { getStatusColor } from '@/services/validation.service';

export default function Section129TrialReview() {
  const { toast } = useToast();
  const [, setLocation] = useLocation();
  const params = useParams<{ runId: string }>();
  const runId = params?.runId ? parseInt(params.runId, 10) : 0;

  const [accounts, setAccounts] = useState<Section129RunAccount[]>([]);
  const [runInfo, setRunInfo] = useState<Section129Run | null>(null);
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [selectedIds, setSelectedIds] = useState<Set<number>>(new Set());
  const [finalReviewComplete, setFinalReviewComplete] = useState(false);
  const [currentPage, setCurrentPage] = useState(1);

  useEffect(() => {
    if (!runId) return;
    const load = async () => {
      setLoading(true);
      try {
        const [accountsData, runsData] = await Promise.all([
          fetchSection129RunAccounts(runId),
          fetchSection129Runs(),
        ]);
        setAccounts(accountsData);
        const run = runsData.find(r => r.runId === runId) || null;
        setRunInfo(run);
        const preSelected = new Set(
          accountsData.filter(a => a.selected).map(a => a.accountId)
        );
        setSelectedIds(preSelected.size > 0 ? preSelected : new Set(accountsData.map(a => a.accountId)));
      } catch (err: any) {
        toast({
          title: 'Failed to Load',
          description: err.message || 'Could not load trial run accounts.',
          variant: 'destructive',
        });
      } finally {
        setLoading(false);
      }
    };
    load();
  }, [runId]);

  const totalPages = Math.ceil(accounts.length / PAGE_SIZE);
  const paginatedAccounts = useMemo(() => {
    const start = (currentPage - 1) * PAGE_SIZE;
    return accounts.slice(start, start + PAGE_SIZE);
  }, [accounts, currentPage]);

  const allOnPageSelected = useMemo(() => {
    if (paginatedAccounts.length === 0) return false;
    return paginatedAccounts.every(a => selectedIds.has(a.accountId));
  }, [paginatedAccounts, selectedIds]);

  const toggleAccount = useCallback((accountId: number) => {
    setSelectedIds(prev => {
      const next = new Set(prev);
      if (next.has(accountId)) {
        next.delete(accountId);
      } else {
        next.add(accountId);
      }
      return next;
    });
  }, []);

  const toggleSelectAll = useCallback(() => {
    setSelectedIds(prev => {
      const next = new Set(prev);
      if (allOnPageSelected) {
        paginatedAccounts.forEach(a => next.delete(a.accountId));
      } else {
        paginatedAccounts.forEach(a => next.add(a.accountId));
      }
      return next;
    });
  }, [allOnPageSelected, paginatedAccounts]);

  const handleSubmit = async () => {
    if (selectedIds.size === 0) {
      toast({
        title: 'No Accounts Selected',
        description: 'Please select at least one account before submitting.',
        variant: 'destructive',
      });
      return;
    }
    setSubmitting(true);
    try {
      const result = await submitSection129TrialReview({
        runId,
        selectedAccountIds: Array.from(selectedIds),
        finalReviewComplete,
      });
      toast({
        title: 'Review Submitted',
        description: result.message || `Successfully submitted review for ${selectedIds.size} account(s).`,
      });
      setLocation('/debt/section129');
    } catch (err: any) {
      toast({
        title: 'Submission Failed',
        description: err.message || 'Failed to submit trial review.',
        variant: 'destructive',
      });
    } finally {
      setSubmitting(false);
    }
  };

  const totalQualifyingAmount = useMemo(() => {
    return accounts
      .filter(a => selectedIds.has(a.accountId))
      .reduce((sum, a) => sum + (a.qualifyingAmount || 0), 0);
  }, [accounts, selectedIds]);

  const totalNoticeFees = useMemo(() => {
    return accounts
      .filter(a => selectedIds.has(a.accountId))
      .reduce((sum, a) => sum + (a.noticeFees || 0), 0);
  }, [accounts, selectedIds]);

  return (
    <PosLayout>
      <div className="flex-1 overflow-y-auto bg-gradient-to-br from-slate-50 via-white to-slate-50">
        <div className="max-w-7xl mx-auto px-3 sm:px-4 lg:px-6 py-4 sm:py-6 space-y-4 sm:space-y-5">
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
            <div className="flex items-center gap-3">
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setLocation('/debt/section129')}
                className="gap-1.5 text-muted-foreground hover:text-foreground"
                data-testid="button-back"
              >
                <ArrowLeft className="w-4 h-4" />
                <span className="hidden sm:inline">Back to Notices</span>
              </Button>
              <div>
                <h1 className="text-lg sm:text-xl font-bold text-foreground tracking-tight flex items-center gap-2" data-testid="text-page-title">
                  <FileCheck className="w-5 h-5 text-amber-600" />
                  Trial Run Review
                </h1>
                <p className="text-xs text-muted-foreground mt-0.5">
                  Review and select accounts for Section 129 notice processing
                </p>
              </div>
            </div>
          </div>

          <Card className="border border-slate-200/80 shadow-sm bg-white/90 backdrop-blur-sm overflow-hidden">
            <CardContent className="p-4 sm:p-5">
              <div className="flex flex-wrap items-center gap-3 sm:gap-6">
                <div className="flex items-center gap-2">
                  <Hash className="w-4 h-4 text-muted-foreground" />
                  <span className="text-xs text-muted-foreground">Run ID</span>
                  <span className="text-sm font-semibold text-foreground" data-testid="text-run-id">
                    {runId || '—'}
                  </span>
                </div>

                <div className="flex items-center gap-2">
                  <Tag className="w-4 h-4 text-muted-foreground" />
                  <span className="text-xs text-muted-foreground">Status</span>
                  <Badge
                    variant="outline"
                    className={`text-xs font-medium ${runInfo ? getStatusColor(runInfo.status) : 'bg-slate-100 text-slate-500'}`}
                    data-testid="badge-run-status"
                  >
                    {runInfo?.status || 'Loading...'}
                  </Badge>
                </div>

                <div className="flex items-center gap-2">
                  <Users className="w-4 h-4 text-muted-foreground" />
                  <span className="text-xs text-muted-foreground">Handover Option</span>
                  <span className="text-sm font-medium text-foreground" data-testid="text-handover-option">
                    {runInfo?.handoverOption || '—'}
                  </span>
                </div>

                <div className="flex items-center gap-2">
                  <Clock className="w-4 h-4 text-muted-foreground" />
                  <span className="text-xs text-muted-foreground">Created</span>
                  <span className="text-sm text-foreground" data-testid="text-date-created">
                    {runInfo?.dateCreated || '—'}
                  </span>
                </div>
              </div>
            </CardContent>
          </Card>

          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            <Card className="border border-slate-200/80 shadow-sm bg-white/90 backdrop-blur-sm">
              <CardContent className="p-3 sm:p-4 text-center">
                <div className="text-xs text-muted-foreground mb-1">Total Accounts</div>
                <div className="text-lg sm:text-xl font-bold text-foreground" data-testid="text-total-accounts">
                  {accounts.length}
                </div>
              </CardContent>
            </Card>
            <Card className="border border-slate-200/80 shadow-sm bg-white/90 backdrop-blur-sm">
              <CardContent className="p-3 sm:p-4 text-center">
                <div className="text-xs text-muted-foreground mb-1">Selected</div>
                <div className="text-lg sm:text-xl font-bold text-blue-600" data-testid="text-selected-count">
                  {selectedIds.size}
                </div>
              </CardContent>
            </Card>
            <Card className="border border-slate-200/80 shadow-sm bg-white/90 backdrop-blur-sm">
              <CardContent className="p-3 sm:p-4 text-center">
                <div className="text-xs text-muted-foreground mb-1">Qualifying Amount</div>
                <div className="text-lg sm:text-xl font-bold text-emerald-600" data-testid="text-qualifying-total">
                  R {totalQualifyingAmount.toLocaleString('en-ZA', { minimumFractionDigits: 2 })}
                </div>
              </CardContent>
            </Card>
            <Card className="border border-slate-200/80 shadow-sm bg-white/90 backdrop-blur-sm">
              <CardContent className="p-3 sm:p-4 text-center">
                <div className="text-xs text-muted-foreground mb-1">Notice Fees</div>
                <div className="text-lg sm:text-xl font-bold text-amber-600" data-testid="text-fees-total">
                  R {totalNoticeFees.toLocaleString('en-ZA', { minimumFractionDigits: 2 })}
                </div>
              </CardContent>
            </Card>
          </div>

          <Card className="border border-slate-200/80 shadow-sm bg-white/90 backdrop-blur-sm overflow-hidden">
            <CardContent className="p-0">
              {loading ? (
                <div className="flex flex-col items-center justify-center py-16 gap-3">
                  <Loader2 className="w-8 h-8 animate-spin text-blue-500" />
                  <p className="text-sm text-muted-foreground">Loading trial run accounts...</p>
                </div>
              ) : accounts.length === 0 ? (
                <div className="flex flex-col items-center justify-center py-16 gap-3">
                  <AlertTriangle className="w-10 h-10 text-amber-400" />
                  <p className="text-sm text-muted-foreground">No accounts found for this trial run.</p>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => setLocation('/debt/section129')}
                    data-testid="button-back-empty"
                  >
                    Back to Notices
                  </Button>
                </div>
              ) : (
                <>
                  <div className="overflow-x-auto">
                    <Table>
                      <TableHeader>
                        <TableRow className="bg-slate-50/80">
                          <TableHead className="w-10">
                            <HelpTip text="Select or deselect all accounts on this page">
                              <Checkbox
                                checked={allOnPageSelected}
                                onCheckedChange={toggleSelectAll}
                                data-testid="checkbox-select-all"
                              />
                            </HelpTip>
                          </TableHead>
                          <TableHead className="text-xs font-semibold text-slate-600">Account No</TableHead>
                          <TableHead className="text-xs font-semibold text-slate-600 hidden sm:table-cell">Address</TableHead>
                          <TableHead className="text-xs font-semibold text-slate-600 hidden md:table-cell">Indigent</TableHead>
                          <TableHead className="text-xs font-semibold text-slate-600 hidden md:table-cell">Rebate</TableHead>
                          <TableHead className="text-xs font-semibold text-slate-600 hidden lg:table-cell">SG Number</TableHead>
                          <TableHead className="text-xs font-semibold text-slate-600 text-right">Days O/S</TableHead>
                          <TableHead className="text-xs font-semibold text-slate-600 text-right">Qualifying Amt</TableHead>
                          <TableHead className="text-xs font-semibold text-slate-600 text-right hidden sm:table-cell">Notice Fees</TableHead>
                        </TableRow>
                      </TableHeader>
                      <TableBody>
                        {paginatedAccounts.map((account) => {
                          const isSelected = selectedIds.has(account.accountId);
                          return (
                            <TableRow
                              key={account.accountId}
                              className={`cursor-pointer transition-colors ${
                                isSelected
                                  ? 'bg-blue-50/60 hover:bg-blue-50/80'
                                  : 'hover:bg-slate-50/60'
                              }`}
                              onClick={() => toggleAccount(account.accountId)}
                              data-testid={`row-account-${account.accountId}`}
                            >
                              <TableCell onClick={(e) => e.stopPropagation()}>
                                <Checkbox
                                  checked={isSelected}
                                  onCheckedChange={() => toggleAccount(account.accountId)}
                                  data-testid={`checkbox-account-${account.accountId}`}
                                />
                              </TableCell>
                              <TableCell className="text-sm font-medium text-foreground" data-testid={`text-account-no-${account.accountId}`}>
                                {account.accountNo}
                              </TableCell>
                              <TableCell className="text-sm text-muted-foreground max-w-[200px] truncate hidden sm:table-cell" title={account.address}>
                                {account.address || '—'}
                              </TableCell>
                              <TableCell className="hidden md:table-cell">
                                <Badge
                                  variant="outline"
                                  className={`text-[10px] ${
                                    account.indigentStatus?.toLowerCase() === 'yes'
                                      ? 'bg-orange-50 text-orange-600 border-orange-200'
                                      : 'bg-slate-50 text-slate-500 border-slate-200'
                                  }`}
                                  data-testid={`badge-indigent-${account.accountId}`}
                                >
                                  {account.indigentStatus || 'No'}
                                </Badge>
                              </TableCell>
                              <TableCell className="hidden md:table-cell">
                                <Badge
                                  variant="outline"
                                  className={`text-[10px] ${
                                    account.rebateStatus?.toLowerCase() === 'yes'
                                      ? 'bg-purple-50 text-purple-600 border-purple-200'
                                      : 'bg-slate-50 text-slate-500 border-slate-200'
                                  }`}
                                  data-testid={`badge-rebate-${account.accountId}`}
                                >
                                  {account.rebateStatus || 'No'}
                                </Badge>
                              </TableCell>
                              <TableCell className="text-xs text-muted-foreground font-mono hidden lg:table-cell">
                                {account.sgNumber || '—'}
                              </TableCell>
                              <TableCell className="text-sm text-right font-medium" data-testid={`text-days-${account.accountId}`}>
                                <span className={account.outstandingDays > 90 ? 'text-red-600' : account.outstandingDays > 60 ? 'text-amber-600' : 'text-foreground'}>
                                  {account.outstandingDays}
                                </span>
                              </TableCell>
                              <TableCell className="text-sm text-right font-medium text-foreground" data-testid={`text-amount-${account.accountId}`}>
                                R {(account.qualifyingAmount || 0).toLocaleString('en-ZA', { minimumFractionDigits: 2 })}
                              </TableCell>
                              <TableCell className="text-sm text-right text-muted-foreground hidden sm:table-cell">
                                R {(account.noticeFees || 0).toLocaleString('en-ZA', { minimumFractionDigits: 2 })}
                              </TableCell>
                            </TableRow>
                          );
                        })}
                      </TableBody>
                    </Table>
                  </div>

                  {totalPages > 1 && (
                    <div className="flex items-center justify-between px-4 py-3 border-t border-slate-100">
                      <span className="text-xs text-muted-foreground" data-testid="text-pagination-info">
                        Page {currentPage} of {totalPages} ({accounts.length} accounts)
                      </span>
                      <div className="flex items-center gap-1">
                        <Button
                          variant="outline"
                          size="sm"
                          disabled={currentPage <= 1}
                          onClick={() => setCurrentPage(p => Math.max(1, p - 1))}
                          data-testid="button-prev-page"
                        >
                          <ChevronLeft className="w-4 h-4" />
                        </Button>
                        <Button
                          variant="outline"
                          size="sm"
                          disabled={currentPage >= totalPages}
                          onClick={() => setCurrentPage(p => Math.min(totalPages, p + 1))}
                          data-testid="button-next-page"
                        >
                          <ChevronRight className="w-4 h-4" />
                        </Button>
                      </div>
                    </div>
                  )}
                </>
              )}
            </CardContent>
          </Card>

          {!loading && accounts.length > 0 && (
            <Card className="border border-slate-200/80 shadow-sm bg-white/90 backdrop-blur-sm">
              <CardContent className="p-4 sm:p-5">
                <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
                  <div className="flex items-center gap-3">
                    <HelpTip text="When enabled, submitting changes the run status from 'Trial Run Review' to 'Trial Run', marking the review as complete.">
                      <div className="flex items-center gap-2.5">
                        <Switch
                          checked={finalReviewComplete}
                          onCheckedChange={setFinalReviewComplete}
                          data-testid="switch-final-review"
                        />
                        <Label className="text-sm font-medium cursor-pointer" htmlFor="final-review">
                          Final Review Complete
                        </Label>
                        {finalReviewComplete && (
                          <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                        )}
                      </div>
                    </HelpTip>
                  </div>

                  <div className="flex items-center gap-2">
                    <Button
                      variant="outline"
                      onClick={() => setLocation('/debt/section129')}
                      className="gap-1.5"
                      data-testid="button-cancel"
                    >
                      <XCircle className="w-4 h-4" />
                      Cancel
                    </Button>
                    <Button
                      onClick={handleSubmit}
                      disabled={submitting || selectedIds.size === 0}
                      className="gap-1.5 bg-blue-600 hover:bg-blue-700 text-white"
                      data-testid="button-submit"
                    >
                      {submitting ? (
                        <Loader2 className="w-4 h-4 animate-spin" />
                      ) : (
                        <Send className="w-4 h-4" />
                      )}
                      Submit Review ({selectedIds.size})
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          )}
        </div>
      </div>
    </PosLayout>
  );
}
